name: check
on: [push, pull_request]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.8
          terraform_wrapper: false

      - name: terraform fmt
        run: terraform fmt -check -recursive -diff

      - name: terraform validate
        run: |
          terraform init -backend=false
          terraform validate

      - uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.64.0

      - name: tflint
        run: |
          tflint --init
          tflint --format compact
        env:
          GITHUB_TOKEN: ${{ github.token }}
